# Generated by Django 3.2.6 on 2021-08-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210831_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='opposum',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
